{% set name = "chars" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antifuchs/chars/archive/v{{ version }}.tar.gz
  sha256: 2f79843a3b1173870b41ebce491a54812b13a44090d0ae30a6f572caa91f0736

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - chars 10

about:
  home: https://github.com/antifuchs/chars
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Command-line tool to display information about unicode characters
  dev_url: https://github.com/antifuchs/chars

extra:
  recipe-maintainers:
    - danielnachun
