context:
  version: 0.7.0

package:
  name: chars
  version: ${{ version }}

source:
  url: https://github.com/antifuchs/chars/archive/v${{ version }}.tar.gz
  sha256: 2f79843a3b1173870b41ebce491a54812b13a44090d0ae30a6f572caa91f0736

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - chars 10

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Command-line tool to display information about unicode characters
  homepage: https://github.com/antifuchs/chars
  repository: https://github.com/antifuchs/chars

extra:
  recipe-maintainers:
    - danielnachun
